name: Build GitHub Pages
on:
  workflow_dispatch: 
  push:
    branches:
      - main
    paths:
      - 'webpage/**'
permissions:
  contents: write 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install packages
        run: pip install \
            mkdocs-material \
            pymdown-extensions \
            mkdocs-awesome-nav \
            mkdocs-material-extensions
      - name: Build documentation
        run: mkdocs gh-deploy --config-file webpage/mkdocs.yml --force 

